'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,Play,Pause} from 'lucide-react';
import YouTubePreview from './youtube-preview';
import ToneHeading from '../tone-heading';
import {Close} from '../chrome';
import type {EpisodeFeed} from './feed';
const CHANNEL='https://www.youtube.com/@SoniqCX';
export default function Podcast({initial}:{initial:EpisodeFeed}){
 const [feed,setFeed]=useState(initial),[playing,setPlaying]=useState(false);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{const enabled=!mq.matches&&document.documentElement.dataset.motion!=='off';setPlaying(enabled)};update();const observer=new MutationObserver(update);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-motion']});mq.addEventListener('change',update);return()=>{observer.disconnect();mq.removeEventListener('change',update)}},[]);
 useEffect(()=>{const abort=new AbortController();const refresh=()=>{if(document.hidden)return;fetch('/api/podcast',{signal:abort.signal}).then(r=>r.ok?r.json() as Promise<EpisodeFeed>:null).then(data=>{if(data?.episodes?.length)setFeed(data)}).catch(()=>{})};refresh();const timer=setInterval(refresh,300000);return()=>{clearInterval(timer);abort.abort()}},[]);
 const latest=feed.episodes[0];
 return <main id="main" className="podcast-page"><section className="podcast-hero"><div className="podcast-copy"><p className="eyebrow">THE SONIQCX PODCAST</p><div className="podcast-brand"><img src="/assets/shift-happens.jpg" alt="SHIFT HAPPENS, hosted by SONIQCX" width="900" height="900"/><span>BIG IDEAS.<br/>REAL CONVERSATIONS.</span></div><ToneHeading as="h1">Shift<br/><span>happens.</span></ToneHeading><p>Cool people. Big ideas. Honest conversations about business, AI, leadership, and the future of customer experience.</p><a className="button" href={CHANNEL} target="_blank" rel="noreferrer">WATCH ON YOUTUBE<ArrowUpRight size={18}/></a></div><div className="podcast-stage"><div className="podcast-video"><img src={latest.thumbnail} alt="" width="720" height="404"/>{playing&&<YouTubePreview id={latest.id} onUnavailable={()=>setPlaying(false)}/>}</div><div className="podcast-video-bar"><span>SHIFT HAPPENS / SONIQCX</span><button onClick={()=>setPlaying(p=>!p)} aria-label={playing?'Pause podcast preview':'Play muted podcast preview'}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?'PAUSE PREVIEW':'PLAY MUTED PREVIEW'}</button></div><p className="podcast-preview-note">{playing?'Sound off. Ideas on.':'Press play for a silent preview.'}</p></div></section><section className="podcast-latest wrap"><div className="episode-kicker"><span className="eyebrow">{feed.fresh?'LATEST EPISODE':'FEATURED EPISODE'}</span><span>FULL CONVERSATIONS / SHIFT HAPPENS</span></div><div className="latest-layout"><div><ToneHeading>{latest.title}</ToneHeading><p>{latest.duration} · SHIFT HAPPENS by SONIQCX</p></div><a className="button" href={`https://www.youtube.com/watch?v=${latest.id}`} target="_blank" rel="noreferrer"><Play size={16}/>WATCH EPISODE<ArrowUpRight size={18}/></a></div></section><section className="podcast-archive wrap"><div className="section-top"><ToneHeading>Keep the<br/>conversation going.</ToneHeading><a className="text-link" href={`${CHANNEL}/videos`} target="_blank" rel="noreferrer">All episodes on YouTube<ArrowUpRight size={18}/></a></div><div className="episode-grid">{feed.episodes.slice(1).map(ep=><a className="episode-card" href={`https://www.youtube.com/watch?v=${ep.id}`} target="_blank" rel="noreferrer" key={ep.id}><div className="episode-thumb"><img src={ep.thumbnail} alt="" width="720" height="404" loading="lazy"/><span>{ep.duration}</span><Play className="episode-play" size={30}/></div><p className="eyebrow">SHIFT HAPPENS</p><h3>{ep.title}</h3><span className="text-link">Watch episode<ArrowUpRight size={16}/></span></a>)}</div></section><Close heading="Big ideas start with a conversation."/></main>
}
