'use client';
import {useState} from 'react';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {ArrowUpRight,Upload} from 'lucide-react';
const positions=['Inbound or Outbound Sales','Telemarketing','Appointment Setting or Lead Generation','Customer Service Voice or Digital','Technical Support Voice or Digital','Leadership or Administration'];
function Choice({label,name,options,required=false,placeholder=false}:{label:string;name:string;options:string[];required?:boolean;placeholder?:boolean}){return <label className="form-field"><span>{label}{required&&' *'}</span><NativeSelect name={name} required={required} defaultValue={placeholder?'':options[0]}>{placeholder&&<option value="">Select an option</option>}{options.map(x=><option key={x} value={x}>{x}</option>)}</NativeSelect></label>}
export default function ApplicationForm(){const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[success,setSuccess]=useState(false),[resume,setResume]=useState(''),[audio,setAudio]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const data=new FormData(form);const cv=data.get('resume') as File, voice=data.get('audio') as File;if(!cv?.size||!voice?.size){setStatus('Please attach your resume and voice recording.');return}if(!/\.(pdf|doc|docx)$/i.test(cv.name)){setStatus('Please use a PDF or Word document for your resume.');return}if(cv.size>10*1024*1024||voice.size>20*1024*1024){setStatus('Please keep your resume below 10 MB and your audio below 20 MB.');return}setBusy(true);setStatus('');setSuccess(false);
 try{const response=await fetch('/api/apply',{method:'POST',body:data});const result=await response.json() as {success?:boolean;error?:string};if(!response.ok||result.success!==true)throw new Error(result.error||'We could not confirm your application. Please try again.');setSuccess(true);setStatus('Your application has been received. Watch your email for the next steps from the Talent team.');form.reset();setResume('');setAudio('')}catch(e){setStatus(e instanceof Error?e.message:'We could not confirm your application. Please try again.')}finally{setBusy(false)}}
 return <form className="application-form" onSubmit={submit} method="post" action="/api/apply" encType="multipart/form-data"><h2>Submit your application.</h2><p>Tell us about yourself and the work you want to do.</p><div className="form-grid"><label className="form-field"><span>Full name *</span><Input name="name" autoComplete="name" required maxLength={160}/></label><label className="form-field"><span>Email *</span><Input name="email" type="email" autoComplete="email" required maxLength={254}/></label><div className="phone-fields"><label className="form-field"><span>Country code *</span><NativeSelect name="phone_country" defaultValue="+1">{[['+1','USA/Canada'],['+44','UK'],['+61','Australia'],['+91','India'],['+63','Philippines'],['+27','South Africa']].map(([code,country])=><option key={code} value={code}>{code} ({country})</option>)}</NativeSelect></label><label className="form-field"><span>Phone number *</span><Input name="phone" type="tel" autoComplete="tel-national" required maxLength={40}/></label></div><label className="form-field"><span>Country of residence *</span><Input name="country" autoComplete="country-name" required maxLength={100}/></label><Choice label="Which position interests you?" name="position" options={positions} required placeholder/><Choice label="How did you hear about us?" name="referral_source" options={['LinkedIn','Facebook','Friend','Job Site','Current Employee']} required placeholder/><Choice label="Are you currently employed?" name="currently_employed" options={['Yes','No']}/><Choice label="When can you start?" name="start_date" options={['Immediately','I need to give notice first','Other']}/></div><div className="upload-fields"><label className="upload-field"><Upload size={22}/><span>CV or resume *</span><p>PDF or Word. Up to 10 MB.</p><Input type="file" name="resume" accept=".pdf,.doc,.docx" required onChange={e=>setResume(e.target.files?.[0]?.name||'')}/>{resume&&<small>{resume}</small>}</label><label className="upload-field"><Upload size={22}/><span>Voice recording *</span><p>A clear, energetic 45-second introduction about your experience and fit for the role. Up to 20 MB.</p><Input type="file" name="audio" accept="audio/*" required onChange={e=>setAudio(e.target.files?.[0]?.name||'')}/>{audio&&<small>{audio}</small>}</label></div><label className="newsletter"><Checkbox name="newsletter_signup" value="yes"/><span>Sign up for news and job updates</span></label><p className="application-privacy">Your application goes to SONIQCX’s Talent team. <a href="/privacy">Read the privacy policy.</a></p><button className="button" type="submit" disabled={busy}>{busy?'Submitting…':'Submit application'}<ArrowUpRight size={18}/></button>{status&&<p className={`form-status ${success?'success':''}`} role="status">{status}</p>}<noscript><p>Submitting this form opens the application response on the next page.</p></noscript></form>}
