'use client';
import {useEffect,useState,useRef} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,Menu,Pause,Play} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger} from '@/components/ui/sheet';
export const CALL='https://calendly.com/justin-9urp/let-s-talk-about-your-goals';
export const CONSULT='https://calendly.com/justin-9urp/contact-center-strategy-call';
export const navigation=[['Home','/'],['SONIQ AI','/soniq-ai'],['Voice AI','/voice-ai'],['Why SONIQCX','/why-soniqcx'],['The CX Courtroom','/cx-courtroom'],['About','/about'],['Our team','/team'],['Careers','/careers'],['Contact','/contact']];
export function CTA({children='Schedule a call',href='/contact',light=false}:{children?:React.ReactNode;href?:string;light?:boolean}){return <a className={`button ${light?'button-light':''}`} href={href}>{children}<ArrowUpRight size={18}/></a>}
export function Chrome({children}:{children:React.ReactNode}){
 const [menu,setMenu]=useState(false),[motion,setMotion]=useState(true);const path=usePathname();const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{setMenu(false)},[path]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');let saved=null;try{saved=localStorage.getItem('soniq-motion')}catch{}const enabled=saved? saved!=='off':!mq.matches;setMotion(enabled);document.documentElement.dataset.motion=enabled?'on':'off';},[]);
 useEffect(()=>{
  let dispose:undefined|(()=>void);let stopped=false;
  const start=()=>{const sc=(window as unknown as {ScrollCraft?:{mount:(el:HTMLElement)=>{destroy?:()=>void}}}).ScrollCraft;if(!stopped&&sc&&root.current&&!root.current.dataset.scMounted){root.current.dataset.scMounted='true';sc.mount(root.current);}};
  if((window as unknown as {ScrollCraft?:unknown}).ScrollCraft)start();else {const script=document.createElement('script');script.src='/scrollcraft/scrollcraft.js';script.onload=start;document.body.appendChild(script);}
  const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('entered');io.unobserve(e.target)}})},{threshold:.12});root.current?.querySelectorAll('[data-enter]').forEach(e=>io.observe(e));
  return()=>{stopped=true;dispose?.();io.disconnect()};
 },[path]);
 function toggle(){const next=!motion;setMotion(next);document.documentElement.dataset.motion=next?'on':'off';try{localStorage.setItem('soniq-motion',next?'on':'off')}catch{}dispatchEvent(new Event('soniq-motion'))}
 return <div ref={root} className="site-shell"><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><a className="brand" href="/" aria-label="SONIQCX home"><img src="/assets/soniqcx.webp" alt="SONIQCX" width="810" height="130"/></a><nav aria-label="Main navigation" className="desktop-nav">{[['The approach','/why-soniqcx'],['Intelligence','/soniq-ai'],['Our team','/team']].map(([name,url])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{name}</a>)}</nav><div className="nav-right"><a className="nav-cta" href="/contact">Let’s talk<ArrowUpRight size={16}/></a><Sheet open={menu} onOpenChange={setMenu}><SheetTrigger asChild><button className="menu-button" aria-label="Open all pages"><Menu size={22}/><span>Menu</span></button></SheetTrigger><SheetContent className="site-menu"><SheetTitle>Explore SONIQCX</SheetTitle><SheetDescription>People. Performance. Possibilities.</SheetDescription><nav aria-label="All pages">{navigation.map(([name,url])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{name}<ArrowUpRight size={20}/></a>)}</nav><div className="menu-foot"><a href="/resources">Services & insights</a><a href="/contact">Schedule a call</a></div></SheetContent></Sheet></div></header>{children}<footer className="site-footer"><div className="footer-top"><img src="/assets/soniqcx.webp" alt="SONIQCX" width="810" height="130"/><p>Human-led. AI-enhanced.<br/>Revenue accountable.</p></div><div className="footer-directory"><nav aria-label="Company pages">{navigation.map(([name,url])=><a href={url} key={url}>{name}</a>)}</nav><nav aria-label="More resources"><a href="/resources">Services & insights</a><a href="/value-proposition">Our value proposition</a><a href="https://pulse.soniq.ai/" target="_blank" rel="noreferrer">Agent dashboard<ArrowUpRight size={14}/></a><a href="https://dashboard.fdm.ooo/admin/client-login.php" target="_blank" rel="noreferrer">Admin dashboard<ArrowUpRight size={14}/></a><a href="https://fdm.ooo" target="_blank" rel="noreferrer">Powered by fdm.ooo<ArrowUpRight size={14}/></a></nav><div className="membership"><span>Member of</span><img src="/assets/usbpoa.webp" alt="US BPO Alliance" width="988" height="450"/></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} SONIQCX</span><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><button onClick={toggle} aria-pressed={!motion}>{motion?<Pause size={12}/>:<Play size={12}/>}Motion {motion?'on':'off'}</button></div></div></footer></div>
}
export function Close({heading='Stop managing CX. Start monetizing it.'}:{heading?:string}){return <section className="close-section"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2>{heading}</h2></div><div className="close-options"><a href={CONSULT}><span>CX Consulting</span><p>Build a revenue-ready strategy.</p><ArrowUpRight/></a><a href={CALL}><span>BPO Operations</span><p>Put performance into practice.</p><ArrowUpRight/></a></div></section>}
