import CountUp from './count-up';
import ToneHeading from './tone-heading';
import {ArrowUpRight} from 'lucide-react';
import {CTA,Close} from './chrome';
import QScene from './q-scene';
import HeroParticles from './hero-particles';
import {CapabilityExplorer,SignalDiagram,BrandFilm,MetricTrace} from './visuals';
import leaders from './leaders.json';
const pillars=[['Outcomes over activity','Revenue scoring replaces handle time. Every conversation is benchmarked against growth KPIs.',['Conversion and upgrade dashboards','Closed-loop revenue attribution']],['Technology with purpose','Workflow automation, AI coaching, and predictive routing create frictionless momentum.',['AI-guided agent co-pilots','Signals-based prioritization']],['Performance with a human pulse','Empathetic storytelling meets data-led scripts, so every touchpoint feels intentional.',['Adaptive playbooks by segment','Continuous enablement loops']],['True partnership','SONIQCX operates as your revenue pod, with transparent reporting, shared dashboards, and aligned incentives.',['Joint revenue ceremonies','Performance-based contracts']]];
export default function Experience(){return <main id="main" className="new-home">
<div className="hero-cover-stage"><section className="immersive-hero" data-sc-act="flow"><div className="hero-atmosphere" aria-hidden="true"/><HeroParticles/><div className="hero-orbit"><QScene/></div><div className="immersive-copy"><p className="eyebrow">PERFORMANCE-BASED CUSTOMER EXPERIENCE</p><ToneHeading as="h1">Revenue<br/><span>lives here.</span></ToneHeading><p>Every call should drive revenue.<span className="hero-copy-second">Not just get answered.</span></p><CTA href="/contact">Let’s talk</CTA></div></section></div>
<div className="home-flow"><section className="performance-section wrap" data-sc-act="flow"><div className="performance-copy"><ToneHeading as="h2">A conversation is<br/><span>only the beginning.</span></ToneHeading><p>SONIQCX is a performance-based BPO that monetizes customer conversations. Our agents are trained to convert, retain, and grow lifetime value, not just reduce handle time.</p><a className="text-link" href="/why-soniqcx">A different kind of CX<ArrowUpRight size={18}/></a></div><div className="performance-stage"><MetricTrace/><div className="performance-metrics"><div><strong><CountUp value="+34"/><span>%</span></strong><p>Average revenue lift</p></div><div><strong><CountUp value="+18"/><span>%</span></strong><p>Retention boost</p></div><div><strong><CountUp value="90"/><span> days</span></strong><p>Time to impact</p></div></div></div></section>
<section className="capabilities-section wrap" data-sc-act="flow"><div className="section-top"><ToneHeading as="h2">More than<br/>an answer.</ToneHeading><p>Traditional BPOs celebrate how many calls they take. We care about what those calls create.</p></div><CapabilityExplorer/></section>
<BrandFilm/>
<section className="intelligence-feature" data-sc-act="flow"><div className="intelligence-art" data-sc-reveal="up" data-sc-reveal-at="0.02 0.30"><SignalDiagram mode="wave"/></div><div className="intelligence-copy"><p className="wordmark-ai">soniq<span>.ai</span></p><ToneHeading as="h2">Human instinct.<br/>Machine precision.<br/><span>One advantage.</span></ToneHeading><p>Customer experience is revenue in motion. We design every interaction to generate measurable outcomes that grow your business.</p><CTA href="/soniq-ai">Explore SONIQ AI</CTA></div><div className="intelligence-features">{[['Human + AI synergy','Human intuition and AI guidance elevate every customer touchpoint with precision.'],['Predictive revenue systems','Forecast demand, prioritize accounts, and deploy resources where they will convert.'],['Performance architecture','Modular operations engineered to scale without sacrificing quality or outcomes.']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section className="pillars-section wrap" data-sc-act="flow"><div className="section-top"><ToneHeading as="h2">Built for<br/>what comes next.</ToneHeading><p>People, technology, and shared accountability. Working as one revenue operation.</p></div><div className="operating-grid">{pillars.map(([title,copy,points],i)=><article key={title as string} className={'operating-pillar pillar-'+i}><div className="pillar-symbol" aria-hidden="true"><span/><span/><span/><span/></div><h3>{title as string}</h3><p>{copy as string}</p><ul>{(points as string[]).map(s=><li key={s}>{s}</li>)}</ul></article>)}</div></section>
<section className="diagnostic-section" data-sc-act="flow"><HeroParticles/><div className="wrap diagnostic-layout"><div className="diagnostic-title"><ToneHeading as="h2">Busy isn’t<br/>the same<br/>as better.</ToneHeading><p>Chasing volume hides the realities that sabotage revenue. We’ve audited hundreds of CX operations. The same patterns show up every time.</p><a className="text-link" href="/cx-courtroom">Enter the CX Courtroom<ArrowUpRight size={18}/></a></div><div className="diagnostic-ledger">{[['Average handle time','↓ 23%','Faster calls, fewer results. Efficiency means nothing if revenue is still walking out the door.'],['Total revenue','↓ 48%','When you reward activity over outcomes, the bottom line keeps sliding the wrong way.'],['Tickets closed','↑ 14%','Volume is up. But if every resolved ticket ends without an upsell, the win is wasted.'],['Total interactions','↑ 5%','Activity is up. Revenue isn’t. That mismatch is the signal that your KPIs are broken.']].map(([title,value,copy])=><article key={title}><div><h3>{title}</h3><strong><CountUp value={value}/></strong></div><p>{copy}</p></article>)}</div></div></section>
<section className="people-preview wrap" data-sc-act="flow"><div className="section-top"><ToneHeading as="h2">Built by people.<br/><span>Driven by possibility.</span></ToneHeading><div><p>The operators, technologists, and leaders who own the impact.</p><a className="text-link" href="/team">Meet our team<ArrowUpRight size={18}/></a></div></div><div className="portrait-strip">{leaders.map(l=><a href={'/team#'+l.id} key={l.id}><div className="portrait-small"><img src={l.image} alt={l.name} width="500" height="500" loading="lazy"/></div><h3>{l.name}</h3><p>{l.title}</p></a>)}</div></section>
<Close/>
</div></main>}
