import {ArrowUpRight} from 'lucide-react';
import {CTA,Close} from './chrome';
import Spectrum from './spectrum';
import leaders from './leaders.json';
const pillars=[
 ['Outcomes over activity','Revenue scoring replaces handle time. Every conversation is benchmarked against growth KPIs.',['Conversion and upgrade dashboards','Closed-loop revenue attribution']],
 ['Technology with purpose','Workflow automation, AI coaching, and predictive routing create frictionless momentum.',['AI-guided agent co-pilots','Signals-based prioritization']],
 ['Performance with a human pulse','Empathetic storytelling meets data-led scripts, so every touchpoint feels intentional.',['Adaptive playbooks by segment','Continuous enablement loops']],
 ['True partnership','SONIQCX operates as your revenue pod, with transparent reporting, shared dashboards, and aligned incentives.',['Joint revenue ceremonies','Performance-based contracts']]
] as const;
export default function Experience(){return <main id="main">
 <section className="home-hero" data-sc-act="flow"><div className="hero-grid" data-sc-parallax="-0.45" aria-hidden="true"/><div className="hero-signal" data-sc-parallax="0.85"><Spectrum/></div><div className="hero-copy"><p className="eyebrow">PERFORMANCE-BASED CUSTOMER EXPERIENCE</p><h1>REVENUE<br/>LIVES <span>HERE.</span></h1><div className="hero-bottom"><p>Every call should drive revenue.<br/>Not just get answered.</p><CTA>Let’s talk performance</CTA></div></div><div className="hero-baseline"><span>PEOPLE / PERFORMANCE / POSSIBILITIES</span><a href="/why-soniqcx">Discover the SONIQCX model<ArrowUpRight size={15}/></a></div></section>
 <section className="intro-section wrap" data-sc-act="flow"><div className="intro-heading"><h2>A conversation is<br/><span>only the beginning.</span></h2><p>SONIQCX is a performance-based BPO that monetizes customer conversations. Our agents are trained to convert, retain, and grow lifetime value, not just reduce handle time.</p></div><div className="metrics"><div><strong>+34<span>%</span></strong><span>Average revenue lift</span></div><div><strong>+18<span>%</span></strong><span>Retention boost</span></div><div><strong>90<span> days</span></strong><span>Time to impact</span></div></div><a className="text-link" href="/why-soniqcx">See how performance-based CX works<ArrowUpRight size={17}/></a></section>
 <section className="diagnostic-section" data-sc-act="flow"><div className="wrap diagnostic-layout"><div className="diagnostic-title"><p className="eyebrow">THE DISCONNECT</p><h2>Busy isn’t<br/>the same<br/>as better.</h2><p>Chasing volume hides the realities that sabotage revenue. We’ve audited hundreds of CX operations. The same patterns show up every time.</p><a className="text-link" href="/cx-courtroom">Where most BPOs go wrong<ArrowUpRight size={17}/></a></div><div className="diagnostic-ledger" data-sc-reveal="up" data-sc-reveal-at="0.02 0.20">{[['Average handle time','↓ 23%','Faster calls, fewer results. Efficiency means nothing if revenue is still walking out the door.'],['Total revenue','↓ 48%','When you reward activity over outcomes, the bottom line keeps sliding the wrong way.'],['Tickets closed','↑ 14%','Volume is up. But if every resolved ticket ends without an upsell, the win is wasted.'],['Total interactions','↑ 5%','Activity is up. Revenue isn’t. That mismatch is the signal that your KPIs are broken.']].map(([title,value,copy],i)=><article key={title} className={i===1?'negative':''}><div><h3>{title}</h3><strong>{value}</strong></div><p>{copy}</p></article>)}</div></div></section>
 <section className="outcome-scene" data-spectrum-act data-sc-act="pin" data-sc-span="2.1"><div className="outcome-stage" data-sc-stage><div className="outcome-heading"><p className="eyebrow">OPERATIONS BECOMES OPPORTUNITY</p><h2>Every interaction.<br/><span>A better outcome.</span></h2><p>Traditional BPOs celebrate how many calls they take.<br/>We care about what those calls create.</p></div><div className="outcome-field"><Spectrum resolve/></div><div className="outcome-labels"><a href="/why-soniqcx#outcomes"><span>Convert.</span><small>Win the customer.</small></a><a href="/why-soniqcx#outcomes"><span>Retain.</span><small>Earn the relationship.</small></a><a href="/why-soniqcx#outcomes"><span>Grow.</span><small>Increase lifetime value.</small></a></div></div></section>
 <section className="pillars-section wrap" data-sc-act="flow"><div className="section-top"><h2>Built to create<br/>what comes next.</h2><p>People, technology, and shared accountability. Working as one revenue operation.</p></div><div className="pillars">{pillars.map(([title,copy,points],i)=><article key={title} data-sc-in><span className="index">0{i+1}</span><div><h3>{title}</h3><p>{copy}</p><ul>{points.map(p=><li key={p}>{p}</li>)}</ul></div></article>)}</div></section>
 <section className="systems-section" data-sc-act="flow"><div className="wrap"><div className="systems-title"><p className="wordmark-ai">soniq<span>.ai</span></p><h2 data-sc-cue="0 1 0.03 0" data-sc-kinetic="lines">Human instinct.<br/>Intelligent systems.<br/><span>One advantage.</span></h2><p>Customer experience is revenue in motion. We design every interaction to generate measurable outcomes that grow your business.</p></div><div className="system-rows">{[['Human + AI synergy','Human intuition and AI guidance elevate every customer touchpoint with precision.'],['Predictive revenue systems','Forecast demand, prioritize accounts, and deploy resources where they will convert.'],['Performance architecture','Modular operations engineered to scale without sacrificing quality or outcomes.']].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><CTA light href="/soniq-ai">Explore SONIQ AI</CTA></div></section>
 <section className="people-preview wrap" data-sc-act="flow"><div className="section-top"><h2>Real people.<br/>Shared ambition.</h2><div><p>Built by operators. Led by people who own the impact.</p><a className="text-link" href="/team">Meet the whole team<ArrowUpRight size={18}/></a></div></div><div className="portrait-strip">{leaders.map(l=><a href={'/team#'+l.id} key={l.id}><div className="portrait-small"><img data-sc-parallax="-0.2" src={l.image} alt={l.name} width="500" height="500" loading="lazy"/></div><h3>{l.name}</h3><p>{l.title}</p></a>)}</div></section>
 <Close/>
 </main>}
