'use client';
import {useState,useId} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';

export function SignalDiagram({mode='network',label='People and intelligent systems working together'}:{mode?:string;label?:string}){
 const id=useId().replace(/:/g,'');
 return <div className={'signal-diagram diagram-'+mode}><svg viewBox="0 0 700 400" role="img" aria-label={label}><defs><linearGradient id={'line-'+id}><stop stopColor="#223c48"/><stop offset=".5" stopColor="#61abbc"/><stop offset="1" stopColor="#ccecf2"/></linearGradient></defs><g fill="none" stroke={'url(#line-'+id+')'}>{Array.from({length:22},(_,i)=>{const y=35+i*15;return <path key={i} className="signal-path" style={{animationDelay:`${i*-.15}s`}} d={mode==='wave'?`M0 ${y} C180 ${y-100},200 ${400-y},350 200 S560 ${y+80},700 ${y}`:`M0 ${y} C180 ${y},180 200,350 200 S510 ${y},700 ${y}`} strokeWidth={i%5===0?1.1:.6}/>})}</g><g className="signal-nodes" fill="#b4dbe4">{[90,220,350,480,610].map((x,i)=><circle key={x} cx={x} cy={200+(i%2?18:-18)} r={i===2?4:2}/>)}</g><path className="signal-transit" d="M0 200H700" fill="none" stroke="#e8f7fa" strokeWidth="2" strokeDasharray="4 696"/></svg><div className="diagram-labels"><span>Customer intent</span><span>Human + AI</span><span>Business value</span></div></div>
}
const capabilities=[{name:'Convert',title:'Make the moment count.',copy:'Equip your team to recognize intent and turn useful conversations into confident buying decisions.',items:['Sales conversations','AI-assisted coaching','Conversion visibility'],outcome:'Win the customer.'},{name:'Retain',title:'Give people a reason to stay.',copy:'Spot frustration early. Give agents the context and judgment to solve the real problem and strengthen the relationship.',items:['Customer care','Churn signals','Contextual handoffs'],outcome:'Earn the relationship.'},{name:'Grow',title:'Build value beyond the first sale.',copy:'Connect service, sales, and technology around the lifetime of a customer. Measure the value created, then keep improving.',items:['Expansion opportunities','Revenue attribution','Shared accountability'],outcome:'Increase lifetime value.'}];
export function CapabilityExplorer(){const [active,setActive]=useState('Convert');return <Tabs value={active} onValueChange={setActive} className="capability-explorer"><TabsList className="capability-tabs">{capabilities.map(c=><TabsTrigger key={c.name} value={c.name}>{c.name}<ArrowUpRight size={20}/></TabsTrigger>)}</TabsList>{capabilities.map(c=><TabsContent key={c.name} value={c.name} className="capability-panel"><div className="capability-text"><h3>{c.title}</h3><p>{c.copy}</p><ul>{c.items.map(s=><li key={s}>{s}</li>)}</ul><a href="/why-soniqcx#outcomes" className="text-link">Explore the model<ArrowUpRight size={17}/></a></div><div className="capability-visual"><SignalDiagram mode={c.name==='Retain'?'wave':'network'}/><strong>{c.outcome}</strong></div></TabsContent>)}</Tabs>}
export function BrandFilm(){return <section className="brand-film" data-sc-act="scrub" data-sc-span="1.8" data-sc-dwell="0.2"><div className="film-stage" data-sc-stage><div className="film-heading"><h2>Revenue.<br/>In motion.</h2><p>Human-led. AI-enhanced.<br/>Accountable for the outcome.</p></div><div className="brand-film-frame"><img className="sc-stage__poster" src="/assets/brand-motion-poster.jpg" alt="SONIQCX Q brand mark"/><video data-sc-scrub data-sc-src="/assets/brand-motion.mp4" muted playsInline preload="none" aria-label="SONIQCX brand motion controlled by scrolling"/><div className="film-edge" aria-hidden="true"/></div></div></section>}
export function MetricTrace(){return <svg className="metric-trace" viewBox="0 0 900 280" aria-hidden="true"><g fill="none" stroke="#315461" strokeWidth=".7">{[50,105,160,215].map(y=><path key={y} d={`M0 ${y}H900`}/>)}{[130,310,490,670,850].map(x=><path key={x} d={`M${x} 0V280`}/>)}</g>{[0,1,2].map(i=><path className="metric-line" key={i} d={`M-20 ${260-i*40} C160 ${275-i*48},220 ${220-i*50},350 ${208-i*50} S610 ${150-i*35},920 ${20+i*35}`} style={{animationDelay:`${i*-.8}s`}} fill="none" stroke={['#d1ecf1','#61abbc','#386c7e'][i]} strokeWidth={i===0?2.3:1.3}/>)}</svg>}
