import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {AIPage,VoicePage,WhyPage,AboutPage,TeamPage,ContactPage,InnerHero} from '../pages-content';
import Courtroom from '../courtroom';
import ApplicationForm from '../application-form';
import {Close} from '../chrome';
import Experience from '../experience';
import source from '../source-content.json';
import {ArrowUpRight} from 'lucide-react';
const aliases:Record<string,string>={'index.php':'','technology-ai.php':'soniq-ai','sales-pitch-deck.php':'why-soniqcx','the-cx-courtroom.php':'cx-courtroom','about.php':'about','team.php':'team','careers.php':'careers','contact.php':'contact','privacy.php':'privacy','terms.php':'terms','voice-ai.php':'voice-ai','value-prop.php':'value-proposition'};
const names:Record<string,string>={'soniq-ai':'SONIQ AI','voice-ai':'Voice AI','why-soniqcx':'Why SONIQCX','about':'About','team':'Our team','careers':'Careers','contact':'Contact','cx-courtroom':'The CX Courtroom','privacy':'Privacy policy','terms':'Terms of service','resources':'Services & insights','value-proposition':'The SONIQCX value proposition'};
const resources=source.filter(s=>!s.slug.endsWith('.php')&&s.slug!=='index');
function resolve(segments:string[]){const raw=segments.join('/');return aliases[raw]??raw}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const path=resolve(slug);const entry=source.find(s=>s.slug===path.replace(/^page\//,'')||s.slug===(path==='value-proposition'?'value-prop.php':path+'.php'));return {title:names[path]||entry?.title?.replace(/\s*[|].*$/,'')||'SONIQCX',description:entry?.description||'Performance-based CX, intelligent technology, and people who own the outcome.'}}
function Legal({type}:{type:'privacy'|'terms'}){const data=source.find(s=>s.slug===type+'.php')!;return <main id="main" className="legal-page"><div className="reading-page"><div className="reading-label">SONIQCX / {type==='privacy'?'PRIVACY':'TERMS'}</div><article className="source-article legal-copy" dangerouslySetInnerHTML={{__html:data.html}}/></div></main>}
function Resource({slug}:{slug:string}){const data=source.find(s=>s.slug===slug);if(!data)notFound();return <main id="main" className="resource-page"><div className="resource-path"><a href="/resources">Services & insights</a><span>/</span><span>{data.title.split('|')[0].trim()}</span></div><div className="resource-layout"><aside><p className="eyebrow">ON THIS PAGE</p><nav aria-label="Article sections">{data.headings.map((h,i)=><a href={'#section-'+(i+1)} key={i}>{h}</a>)}</nav><a className="button" href="/contact">Talk to our team<ArrowUpRight size={17}/></a></aside><article className="source-article" dangerouslySetInnerHTML={{__html:data.html}}/></div><Close/></main>}
function Resources(){return <main id="main"><InnerHero label="SERVICES & INSIGHTS" title={<>A better way<br/><span>to run CX.</span></>} copy="Explore the operating models, services, and industry expertise behind performance-based customer experience."/><section className="resource-index wrap">{[['Performance-based services',resources.filter(s=>/^(performance-based|pay-for-performance-bpo$|outcome-based|revenue-based|pay-for-performance-call-center)/.test(s.slug))],['Pricing & operating models',resources.filter(s=>/^(traditional|pay-for-performance-bpo-contracts|why-hourly|revenue-share|call-center)/.test(s.slug))],['Industry expertise & comparisons',resources.filter(s=>!/^(performance-based|pay-for-performance|outcome-based|revenue-based|traditional|why-hourly|revenue-share|call-center)/.test(s.slug))]].map(([heading,items])=><div key={heading as string}><h2>{heading as string}</h2><div className="resource-links">{(items as typeof resources).map(s=><a href={'/page/'+s.slug} key={s.slug}><h3>{s.title.split('|')[0].trim()}</h3><ArrowUpRight size={21}/></a>)}</div></div>)}</section><Close/></main>}
function Careers(){return <main id="main"><InnerHero label="CAREERS AT SONIQCX" title={<>Let’s work<br/><span>together.</span></>} copy="Join a team that transforms customer experience into revenue."/><section className="careers-layout wrap"><aside><h2>Make your<br/>next move count.</h2><p>Ready to join a performance-based BPO that monetizes customer conversations? Start your application here.</p><h3>A few tips before you start.</h3><ul><li>Upload your CV or resume in PDF or Word format.</li><li>Monitor your email for follow-ups and assessments from our Talent team.</li><li>Submit assessments within the requested timeframe.</li><li>Keep your voice recording clear and energetic.</li></ul><p>Record your introduction with your phone or computer, or use <a href="https://vocaroo.com" target="_blank" rel="noreferrer">Vocaroo</a>.</p><a className="text-link" href="/team">Meet your future team<ArrowUpRight size={17}/></a></aside><ApplicationForm/></section></main>}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=resolve(slug);switch(path){case '':return <Experience/>;case 'soniq-ai':return <AIPage/>;case 'voice-ai':return <VoicePage/>;case 'why-soniqcx':return <WhyPage/>;case 'cx-courtroom':return <Courtroom/>;case 'about':return <AboutPage/>;case 'team':return <TeamPage/>;case 'contact':return <ContactPage/>;case 'careers':return <Careers/>;case 'privacy':return <Legal type="privacy"/>;case 'terms':return <Legal type="terms"/>;case 'resources':return <Resources/>;case 'value-proposition':return <Resource slug="value-prop.php"/>;default:if(path.startsWith('page/')&&resources.some(s=>s.slug===path.slice(5)))return <Resource slug={path.slice(5)}/>;notFound()}}
